#!/bin/bash

#we can use directly the function name with () brackets OR with function: NAME without () brackets.
log() {
  local MESSAGE="${@}"
  if [[ "${VERBOSE}" = 'true' ]]
  then
    echo "${MESSAGE}"
  fi
#logger command to log messages to syslog -t for tag followed by the tag name and message.
  logger -t mohit12:sh "${MESSAGE}"
}


backup_file() {

#This function creates a backup of file, Returns a non zero status on error.

  local FILE="${1}"

#Make sure the file exists.

  if [[ -f "${FILE}" ]]
  then
     local BACKUP_FIILE="/var/tmp/$(basename ${FILE}).$(date +%F-%N)"
     log "Backing up ${FILE} to ${BACKUP_FILE}."

#The exit status of the function will be the exit status of the cp command. -p to preserver the date and timestamp of the original fi



testing this script........................
